#!/bin/bash
# 🚀 V1 STAGING DEPLOYMENT - ROBUST DEMO MODE
# Run these commands manually (Fly CLI not accessible in build environment)

set -e

echo "════════════════════════════════════════════════════════════════"
echo "🚀 V1 STAGING DEPLOYMENT - DEMO MODE (Server Safety First)"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "📋 STEP 1: Set Secrets (Staging)"
echo "────────────────────────────────────────────────────────────────"
echo "Run these commands:"
echo ""
echo "fly secrets set VITE_DEMO_MODE=true SERVER_DEMO_MODE=true VITE_FEATURE_UNIFIED_DASH=true"
echo ""
echo "Why both flags?"
echo "  • VITE_DEMO_MODE=true     → Client bypasses Supabase (compile-time)"
echo "  • SERVER_DEMO_MODE=true   → Server uses stub client (runtime)"
echo "  • VITE_FEATURE_UNIFIED_DASH=true → Enables unified dashboard"
echo ""
echo "Verify secrets are set:"
echo "fly secrets list"
echo ""
read -p "Press Enter after setting secrets..."
echo ""

echo "📦 STEP 2: Deploy with Cache Bust"
echo "────────────────────────────────────────────────────────────────"
echo "Run this command:"
echo ""
echo "fly deploy --build-arg NO_CACHE=\$(date +%s)"
echo ""
echo "Expected output:"
echo "  ✓ client built in ~11s"
echo "  ✓ server built in ~0.3s"
echo "  ==> Successfully deployed"
echo ""
read -p "Press Enter after deployment completes..."
echo ""

echo "🔍 STEP 3: Verify Server Logs"
echo "────────────────────────────────────────────────────────────────"
echo "Run this command:"
echo ""
echo "fly logs --since 5m | grep -E 'DEMO MODE|Supabase'"
echo ""
echo "Expected output (GOOD SIGNS ✅):"
echo "  [DEMO MODE] Server bypassing Supabase - using stub client"
echo "  🚀 Fusion Starter server running on port 8080"
echo ""
echo "Red flags (BAD - report if you see these ❌):"
echo "  Error: Missing SUPABASE_URL"
echo "  TypeError: Failed to fetch"
echo "  Invalid API key"
echo ""
read -p "Press Enter after verifying logs..."
echo ""

echo "🏥 STEP 4: Health Check"
echo "────────────────────────────────────────────────────────────────"
echo "Run this command (replace YOUR_APP with your Fly app name):"
echo ""
echo "curl -sI https://YOUR_APP.fly.dev/health"
echo ""
echo "Expected: HTTP/2 200"
echo ""
read -p "Press Enter after health check passes..."
echo ""

echo "🌐 STEP 5: Staging Validation (Fast Path)"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "Open in browser: https://YOUR_APP.fly.dev/dashboard"
echo ""
echo "Browser DevTools → Console Tab:"
echo "  ✅ [DEMO MODE] Using mock auth user"
echo "  ✅ [DEMO MODE] Using mock brands"
echo "  ✅ [Analytics] dash_view: { ..., demo_mode: true }"
echo "  ❌ NO Supabase errors"
echo ""
echo "Browser DevTools → Network Tab:"
echo "  1. Filter by 'supabase.co'"
echo "  2. Expected: 0 requests to Supabase"
echo "  3. All /api/* calls return 200"
echo ""
echo "Test all 4 core routes:"
echo "  • /dashboard        → KPIs render"
echo "  • /analytics        → Charts display"
echo "  • /admin/billing    → Table loads"
echo "  • /client-portal    → Read-only (no edit/delete buttons)"
echo ""
echo "Test interactions:"
echo "  • Toggle light/dark mode → colors legible + on-brand"
echo "  • Change brand selector → all cards update"
echo "  • Change period picker → all charts update"
echo ""
read -p "Press Enter after validation..."
echo ""

echo "📸 STEP 6: Capture Proof Artifacts"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "Screenshots (8 total):"
echo "  Desktop (1920x1080) - Light mode:"
echo "    • /dashboard"
echo "    • /analytics"
echo "  Desktop (1920x1080) - Dark mode:"
echo "    • /dashboard"
echo "    • /analytics"
echo "  Mobile (375x667) - Light mode:"
echo "    • /dashboard"
echo "    • /client-portal"
echo "  Mobile (375x667) - Dark mode:"
echo "    • /dashboard"
echo "    • /client-portal"
echo ""
echo "Looms (4 videos, ≤2 min each):"
echo "  1. Agency Flow:"
echo "     - Load /dashboard → show KPIs"
echo "     - Navigate /analytics → show charts"
echo "     - Visit /content-queue"
echo "     - Visit /approvals"
echo "     - Export CSV"
echo ""
echo "  2. Client Flow:"
echo "     - Load /client-portal"
echo "     - Verify NO edit/delete buttons"
echo "     - Export data"
echo "     - Show console (clean)"
echo ""
echo "  3. Filter Sync Demo:"
echo "     - Change brand: Acme Corp → GreenLeaf Organics"
echo "     - All KPIs update simultaneously"
echo "     - Change period: Week → Month"
echo "     - All charts update simultaneously"
echo "     - Show console analytics events"
echo ""
echo "  4. Dark Mode + Mobile:"
echo "     - Toggle dark mode"
echo "     - Verify contrast/colors"
echo "     - Mobile viewport (375px)"
echo "     - Navigate routes"
echo ""
echo "Performance (Lighthouse - Mobile, Throttled):"
echo "  Pages: /dashboard, /analytics"
echo "  Capture: LCP, INP, CLS scores"
echo "  Targets: LCP <2.0s, INP <150ms, CLS <0.1"
echo ""
echo "A11y (axe DevTools):"
echo "  Pages: /dashboard, /analytics, /admin/billing, /client-portal"
echo "  Expected: 0 serious/critical violations"
echo ""
echo "Telemetry (Console Screenshot):"
echo "  Filter console by '[Analytics]'"
echo "  Verify events:"
echo "    • dash_view"
echo "    • dash_filter_applied"
echo "    �� dash_brand_switched"
echo "    • dash_export (if wired)"
echo "  All events must include: demo_mode: true"
echo ""
echo "Build Logs:"
echo "  fly logs --since 5m > staging-build-logs.txt"
echo "  Capture last 20 lines showing clean startup"
echo ""
read -p "Press Enter after capturing all artifacts..."
echo ""

echo "🔧 STEP 7: Edge Polish (10 min)"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "Server console hygiene:"
echo "  ✅ Only ONE [DEMO MODE] log per context on first load"
echo "  ✅ No duplicate/verbose logs"
echo ""
echo "Secrets hygiene:"
echo "  Search dist bundle for leaked secrets:"
echo "  grep -r 'supabase' dist/ | grep -v 'demo.supabase.co'"
echo "  Expected: No matches (or only demo URL)"
echo ""
echo "Flags independence:"
echo "  Test both combinations on staging:"
echo "  • VITE_DEMO_MODE=true + VITE_FEATURE_UNIFIED_DASH=false"
echo "  • VITE_DEMO_MODE=true + VITE_FEATURE_UNIFIED_DASH=true"
echo "  Demo mode must not force unified flag"
echo ""
read -p "Press Enter after polish..."
echo ""

echo "✅ STEP 8: Post GO Note"
echo "──���─────────────────────────────────────────────────────────────"
echo ""
echo "Reply in chat with this format:"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "✅ V1 STAGING LIVE"
echo ""
echo "**Staging URL:** https://YOUR_APP.fly.dev"
echo "**Deployed At:** $(date)"
echo "**Build Time:** ~11s (client) + ~0.3s (server)"
echo ""
echo "**Flags Set:**"
echo "✅ VITE_DEMO_MODE=true"
echo "✅ SERVER_DEMO_MODE=true"
echo "✅ VITE_FEATURE_UNIFIED_DASH=true"
echo ""
echo "**Server Logs:**"
echo "✅ [DEMO MODE] Server bypassing Supabase - using stub client"
echo "✅ 🚀 Fusion Starter server running on port 8080"
echo ""
echo "**Client Console:**"
echo "✅ [DEMO MODE] Using mock auth user"
echo "✅ [DEMO MODE] Using mock brands"
echo "✅ [Analytics] dash_view: { ..., demo_mode: true }"
echo ""
echo "**Network Tab:**"
echo "✅ 0 requests to supabase.co"
echo "✅ All /api/* endpoints returning 200"
echo ""
echo "**Routes Verified:**"
echo "✅ /dashboard - KPIs render, no errors"
echo "✅ /analytics - Charts display with mock data"
echo "✅ /admin/billing - Billing table loads"
echo "✅ /client-portal - Read-only enforced (no edit/delete CTAs)"
echo ""
echo "**Interactions:**"
echo "✅ Light/dark toggle → legible + on-brand"
echo "✅ Brand selector → all cards update"
echo "✅ Period picker → all charts update"
echo ""
echo "**Proof Artifacts:**"
echo "📸 Screenshots: [8 attached/linked]"
echo "🎬 Looms: [4 videos, ≤2 min each]"
echo "⚡ Lighthouse: LCP [X]s, INP [X]ms, CLS [X]"
echo "♿ axe: 0 serious/critical violations"
echo "📊 Telemetry: All events tagged demo_mode: true"
echo "📝 Build logs: [attached - last 20 lines clean]"
echo ""
echo "**Known Issues:**"
echo "- None blocking V1 ✅"
echo ""
echo "**Next Steps:**"
echo "- Review proof artifacts"
echo "- Get stakeholder sign-off"
echo "- Plan production canary rollout"
echo "────────────────────────────────────────────────────────────────"
echo ""

echo ""
echo "════════════════════════════════════════���═══════════════════════"
echo "🎯 DEPLOYMENT COMPLETE - READY FOR V1 STAGING VALIDATION"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "All steps completed. Post the GO note above in chat."
echo ""
