#!/bin/bash

# 🚀 V1 STAGING DEPLOYMENT COMMANDS
# Run these commands manually (Fly CLI blocked in environment)

set -e

echo "📋 Pre-Deployment Checklist"
echo "=============================="
echo ""

echo "Step 1: Verify environment variables"
echo "fly secrets list"
echo ""
echo "Expected:"
echo "  VITE_DEMO_MODE=true"
echo "  VITE_FEATURE_UNIFIED_DASH=true"
echo ""

echo "Step 2: Set variables if missing"
echo "fly secrets set VITE_DEMO_MODE=true"
echo "fly secrets set VITE_FEATURE_UNIFIED_DASH=true"
echo ""

echo "Step 3: Deploy with cache bust"
echo "fly deploy --build-arg NO_CACHE=\$(date +%s)"
echo ""

echo "Step 4: Monitor deployment"
echo "fly logs --since 5m"
echo ""
echo "Look for:"
echo "  ✅ [DEMO MODE] Server using mock Supabase credentials"
echo "  ✅ 🚀 Fusion Starter server running on port 8080"
echo "  ❌ Error: Missing SUPABASE_URL (should NOT appear)"
echo ""

echo "Step 5: Test staging URL"
echo "Open: https://YOUR_APP_NAME.fly.dev/dashboard"
echo ""
echo "DevTools Checklist:"
echo "  Console Tab:"
echo "    ✅ [DEMO MODE] Using mock auth user"
echo "    ✅ [DEMO MODE] Using mock brands"
echo "    ✅ [Analytics] dash_view: { ..., demo_mode: true }"
echo "    ❌ NO Supabase errors"
echo ""
echo "  Network Tab:"
echo "    ✅ Filter by 'supabase.co' → 0 requests"
echo "    ✅ All /api/* calls return 200"
echo ""

echo "Step 6: Test core routes"
echo "Visit and verify each loads without 500:"
echo "  1. /dashboard"
echo "  2. /analytics"
echo "  3. /admin/billing"
echo "  4. /client-portal"
echo ""

echo "Step 7: Capture proof artifacts"
echo "=============================="
echo ""
echo "Screenshots (8 total):"
echo "  Desktop (1920x1080):"
echo "    - Light: /dashboard"
echo "    - Dark: /dashboard"
echo "    - Light: /analytics"
echo "    - Dark: /analytics"
echo "  Mobile (375x667):"
echo "    - Light: /dashboard"
echo "    - Dark: /dashboard"
echo "    - Light: /client-portal"
echo "    - Dark: /client-portal"
echo ""

echo "Looms (4 videos, ≤2 min each):"
echo "  1. Agency Flow:"
echo "     - Load /dashboard → KPIs visible"
echo "     - Navigate /analytics → charts render"
echo "     - Visit /content-queue → content loads"
echo "     - Visit /approvals → pending items"
echo "     - Export → CSV downloads"
echo ""
echo "  2. Client Flow:"
echo "     - Load /client-portal"
echo "     - Verify NO edit/delete buttons"
echo "     - Export data → CSV downloads"
echo "     - Show console (demo mode logs only)"
echo ""
echo "  3. Filter Sync:"
echo "     - Change brand: Acme → GreenLeaf"
echo "     - All KPIs update"
echo "     - Change period: Week → Month"
echo "     - All charts update"
echo "     - Console shows analytics events"
echo ""
echo "  4. Dark Mode + Mobile:"
echo "     - Toggle dark mode"
echo "     - Verify contrast/colors"
echo "     - Mobile viewport (375px)"
echo "     - Navigate routes"
echo "     - Show responsive behavior"
echo ""

echo "Performance (Lighthouse):"
echo "  Pages: /dashboard, /analytics"
echo "  Targets: LCP <2.0s, INP <150ms, CLS <0.1"
echo ""

echo "A11y (axe DevTools):"
echo "  Pages: /dashboard, /analytics, /admin/billing, /client-portal"
echo "  Target: 0 serious/critical violations"
echo ""

echo "Telemetry (Console Screenshot):"
echo "  Filter: [Analytics]"
echo "  Verify: All events have demo_mode: true"
echo ""

echo "Build Logs:"
echo "  fly logs --since 5m > build-logs.txt"
echo ""

echo ""
echo "📝 Post-Deployment Report Template"
echo "=============================="
echo ""
echo "✅ V1 STAGING LIVE"
echo ""
echo "**Staging URL:** https://YOUR_APP_NAME.fly.dev"
echo "**Build Time:** ~11s (client) + ~0.3s (server)"
echo "**Demo Mode:** ✅ Active"
echo "**Supabase Calls:** 0 (bypassed)"
echo ""
echo "**Routes Verified:**"
echo "✅ /dashboard - Loads, KPIs render"
echo "✅ /analytics - Charts display"
echo "✅ /admin/billing - Table loads"
echo "✅ /client-portal - Read-only enforced"
echo ""
echo "**Console Logs:**"
echo "✅ [DEMO MODE] Server using mock Supabase credentials"
echo "✅ [DEMO MODE] Using mock auth user"
echo "✅ [DEMO MODE] Using mock brands"
echo "✅ [Analytics] events tagged with demo_mode: true"
echo ""
echo "**Network Tab:**"
echo "✅ 0 requests to supabase.co"
echo ""
echo "**Known Issues:**"
echo "- None blocking V1"
echo ""
echo "**Artifacts:**"
echo "- Screenshots: [Link]"
echo "- Looms: [Link]"
echo "- Perf metrics: [Lighthouse JSON]"
echo "- A11y audit: [axe results]"
echo "- Telemetry: [Console screenshot]"
echo "- Build logs: [Fly logs]"
echo ""
echo "**Next Steps:**"
echo "- Review proof artifacts"
echo "- Get stakeholder approval"
echo "- Plan production rollout (canary)"
echo ""

echo ""
echo "🎯 Quick Validation Commands"
echo "=============================="
echo ""
echo "# Check server logs for demo mode"
echo "fly logs --since 5m | grep -i 'DEMO MODE'"
echo ""
echo "# Check for errors"
echo "fly logs --since 5m | grep -i error"
echo ""
echo "# Monitor real-time"
echo "fly logs"
echo ""
echo "# Check app status"
echo "fly status"
echo ""
echo "# Check deployment history"
echo "fly releases"
echo ""

echo ""
echo "✅ All commands ready. Execute manually in your terminal."
