import { useBrand } from '@/contexts/BrandContext';
import { Button } from '@/components/ui/button';
import { FileText, Image, TrendingUp, Calendar, ArrowRight, Sparkles } from 'lucide-react';

export default function Dashboard() {
  const { currentBrand } = useBrand();

  if (!currentBrand) {
    return (
      <div className="flex h-full items-center justify-center p-8">
        <div className="text-center max-w-md">
          <Sparkles className="mx-auto h-12 w-12 text-muted-foreground mb-4" />
          <h2 className="text-xl font-semibold mb-2">No brand selected</h2>
          <p className="text-muted-foreground mb-4">
            Create or select a brand to get started with Aligned AI.
          </p>
          <Button asChild>
            <a href="/brands">Manage Brands</a>
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 space-y-8">
      <div>
        <h1 className="text-3xl font-bold">Dashboard</h1>
        <p className="text-muted-foreground mt-1">
          Welcome back! Here's what's happening with {currentBrand.name}.
        </p>
      </div>

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
        <StatCard
          title="Content Items"
          value="24"
          subtitle="12 scheduled"
          icon={<FileText className="h-5 w-5" />}
          trend="+8%"
        />
        <StatCard
          title="Assets"
          value="156"
          subtitle="82 images, 74 docs"
          icon={<Image className="h-5 w-5" />}
          trend="+12"
        />
        <StatCard
          title="Engagement"
          value="3.2k"
          subtitle="This month"
          icon={<TrendingUp className="h-5 w-5" />}
          trend="+24%"
        />
        <StatCard
          title="Next Publish"
          value="Today"
          subtitle="3 posts at 2:00 PM"
          icon={<Calendar className="h-5 w-5" />}
        />
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <div className="rounded-xl border bg-card p-6">
          <h3 className="text-lg font-semibold mb-4">Recent Activity</h3>
          <div className="space-y-3">
            <ActivityItem
              agent="Doc Agent"
              action="Generated 3 blog post drafts"
              time="2 hours ago"
            />
            <ActivityItem
              agent="Design Agent"
              action="Created Instagram carousel template"
              time="5 hours ago"
            />
            <ActivityItem
              agent="Advisor Agent"
              action="Recommended new posting schedule"
              time="1 day ago"
            />
            <ActivityItem
              agent="Manual"
              action="New asset uploaded: brand-logo-2024.png"
              time="2 days ago"
            />
          </div>
        </div>

        <div className="rounded-xl border bg-card p-6">
          <h3 className="text-lg font-semibold mb-4">AI Agent Status</h3>
          <div className="space-y-4">
            <AgentStatus
              name="Doc Agent"
              subtitle="Aligned Words"
              status="active"
              description="Ready to generate content"
            />
            <AgentStatus
              name="Design Agent"
              subtitle="Aligned Creative"
              status="active"
              description="Templates synced"
            />
            <AgentStatus
              name="Advisor Agent"
              subtitle="Aligned Insights"
              status="analyzing"
              description="Analyzing last month's performance"
            />
          </div>
        </div>
      </div>

      <div className="rounded-xl border bg-gradient-to-br from-primary/10 via-fuchsia-500/10 to-sky-500/10 p-6">
        <div className="flex items-start justify-between">
          <div>
            <h3 className="text-lg font-semibold mb-2">Monthly Content Engine</h3>
            <p className="text-sm text-muted-foreground max-w-lg">
              Next month's content will be automatically generated by the 10th. Review and approve
              drafts in the Calendar.
            </p>
          </div>
          <Button variant="outline" className="gap-2">
            View Calendar <ArrowRight className="h-4 w-4" />
          </Button>
        </div>
      </div>
    </div>
  );
}

function StatCard({
  title,
  value,
  subtitle,
  icon,
  trend,
}: {
  title: string;
  value: string;
  subtitle: string;
  icon: React.ReactNode;
  trend?: string;
}) {
  return (
    <div className="rounded-xl border bg-card p-6">
      <div className="flex items-center justify-between mb-2">
        <span className="text-sm text-muted-foreground">{title}</span>
        <div className="text-muted-foreground">{icon}</div>
      </div>
      <div className="text-2xl font-bold">{value}</div>
      <div className="flex items-center justify-between mt-1">
        <p className="text-xs text-muted-foreground">{subtitle}</p>
        {trend && <span className="text-xs text-green-600 font-medium">{trend}</span>}
      </div>
    </div>
  );
}

function ActivityItem({ agent, action, time }: { agent: string; action: string; time: string }) {
  return (
    <div className="flex items-start gap-3 text-sm">
      <div className="mt-0.5 h-2 w-2 rounded-full bg-primary" />
      <div className="flex-1">
        <p className="font-medium">{agent}</p>
        <p className="text-muted-foreground">{action}</p>
      </div>
      <span className="text-xs text-muted-foreground">{time}</span>
    </div>
  );
}

function AgentStatus({
  name,
  subtitle,
  status,
  description,
}: {
  name: string;
  subtitle: string;
  status: 'active' | 'analyzing' | 'idle';
  description: string;
}) {
  const statusColors = {
    active: 'bg-green-500',
    analyzing: 'bg-yellow-500',
    idle: 'bg-gray-400',
  };

  return (
    <div className="flex items-start gap-3">
      <div className={`mt-1 h-2 w-2 rounded-full ${statusColors[status]}`} />
      <div className="flex-1">
        <div className="flex items-baseline gap-2">
          <p className="font-medium">{name}</p>
          <span className="text-xs text-muted-foreground">{subtitle}</span>
        </div>
        <p className="text-sm text-muted-foreground">{description}</p>
      </div>
    </div>
  );
}
