import { UnauthenticatedLayout } from "@/components/layout/UnauthenticatedLayout";
import SiteHeader from "@/components/site/SiteHeader";
import SiteFooter from "@/components/site/SiteFooter";
import { FileText } from "lucide-react";

export default function Terms() {
  return (
    <UnauthenticatedLayout>
      <SiteHeader />

      {/* Hero Section */}
      <section className="bg-gradient-to-b from-slate-50 to-white pt-32 pb-16 px-4 sm:px-6 md:px-8">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 bg-white border border-slate-200 rounded-full px-4 py-2 mb-6 shadow-sm">
            <FileText className="w-4 h-4 text-slate-600" />
            <span className="text-sm font-semibold text-slate-900">
              Last Updated: January 2025
            </span>
          </div>

          <h1 className="text-4xl sm:text-5xl md:text-6xl font-black text-slate-900 mb-6 leading-tight">
            Terms of Service
          </h1>

          <p className="text-lg text-slate-600">
            Please read these terms carefully before using Aligned AI.
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 px-4 sm:px-6 md:px-8 bg-white">
        <div className="max-w-4xl mx-auto prose prose-lg prose-slate">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using Aligned AI ("the Service"), you agree to be
            bound by these Terms of Service ("Terms"). If you do not agree, do
            not use the Service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            Aligned AI is a content creation and marketing platform that uses
            artificial intelligence to help brands and agencies plan, create,
            schedule, and analyze content across multiple channels.
          </p>

          <h2>3. Account Registration</h2>
          <h3>3.1 Eligibility</h3>
          <p>
            You must be at least 18 years old to use the Service. By creating an
            account, you represent that you meet this requirement.
          </p>

          <h3>3.2 Account Responsibility</h3>
          <ul>
            <li>
              You are responsible for maintaining the confidentiality of your
              account credentials
            </li>
            <li>
              You are responsible for all activities that occur under your
              account
            </li>
            <li>You must notify us immediately of any unauthorized access</li>
            <li>You may not share your account with others</li>
          </ul>

          <h2>4. Subscription and Billing</h2>
          <h3>4.1 Pricing</h3>
          <p>
            Current pricing is available at aligned.ai/pricing. Prices are
            subject to change with 30 days' notice.
          </p>

          <h3>4.2 Payment Terms</h3>
          <ul>
            <li>Subscriptions are billed monthly in advance</li>
            <li>All fees are non-refundable except as required by law</li>
            <li>You authorize us to charge your payment method on file</li>
            <li>Failed payments may result in service suspension</li>
          </ul>

          <h3>4.3 Free Trial</h3>
          <p>
            We offer a 7-day free trial for new users. After the trial, your
            subscription begins automatically unless you cancel.
          </p>

          <h3>4.4 Cancellation</h3>
          <p>
            You may cancel your subscription at any time with 30 days' notice.
            Cancellation takes effect at the end of your current billing period.
          </p>

          <h2>5. Acceptable Use</h2>
          <p>You agree NOT to:</p>
          <ul>
            <li>Violate any laws or regulations</li>
            <li>Infringe on intellectual property rights</li>
            <li>Upload malicious code or viruses</li>
            <li>Attempt to gain unauthorized access to the platform</li>
            <li>Use the Service to harass, abuse, or harm others</li>
            <li>Generate spam or misleading content</li>
            <li>Resell or redistribute the Service without authorization</li>
            <li>Reverse engineer or copy any features or technology</li>
          </ul>

          <h2>6. Content Ownership and Licensing</h2>
          <h3>6.1 Your Content</h3>
          <p>
            You retain ownership of all content you create, upload, or generate
            using the Service. By using the Service, you grant us a limited
            license to process, store, and display your content solely to
            provide the Service.
          </p>

          <h3>6.2 AI-Generated Content</h3>
          <p>
            Content generated by our AI is provided to you under a non-exclusive
            license. You are responsible for reviewing and approving all
            AI-generated content before publication.
          </p>

          <h3>6.3 Platform Content</h3>
          <p>
            All platform features, interfaces, and technology are owned by
            Aligned AI and protected by intellectual property laws.
          </p>

          <h2>7. Third-Party Integrations</h2>
          <p>
            The Service integrates with third-party platforms (e.g., Facebook,
            LinkedIn). Your use of these integrations is subject to their
            respective terms of service. We are not responsible for third-party
            services.
          </p>

          <h2>8. Data and Privacy</h2>
          <p>
            Our collection and use of your data is governed by our Privacy
            Policy. By using the Service, you consent to our data practices.
          </p>

          <h2>9. Disclaimers and Limitations</h2>
          <h3>9.1 Service Availability</h3>
          <p>
            The Service is provided "AS IS" and "AS AVAILABLE." We do not
            guarantee uninterrupted or error-free service.
          </p>

          <h3>9.2 AI Accuracy</h3>
          <p>
            While our AI strives for accuracy, we do not guarantee that
            AI-generated content is error-free or suitable for all purposes. You
            are responsible for reviewing content before use.
          </p>

          <h3>9.3 Limitation of Liability</h3>
          <p>
            To the fullest extent permitted by law, Aligned AI shall not be
            liable for any indirect, incidental, special, or consequential
            damages arising from your use of the Service.
          </p>

          <h2>10. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless Aligned AI from any claims,
            damages, or expenses arising from your use of the Service or
            violation of these Terms.
          </p>

          <h2>11. Termination</h2>
          <p>
            We may suspend or terminate your account at any time for violation
            of these Terms. Upon termination:
          </p>
          <ul>
            <li>Your access to the Service will be revoked</li>
            <li>You remain responsible for any outstanding fees</li>
            <li>You may request export of your data within 30 days</li>
          </ul>

          <h2>12. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. Material changes will
            be communicated via email or platform notification. Continued use
            after changes constitutes acceptance.
          </p>

          <h2>13. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the jurisdiction in which
            Aligned AI operates, without regard to conflict of law principles.
          </p>

          <h2>14. Dispute Resolution</h2>
          <p>
            Any disputes arising from these Terms shall be resolved through
            binding arbitration in accordance with applicable arbitration rules.
          </p>

          <h2>15. Miscellaneous</h2>
          <ul>
            <li>
              <strong>Entire Agreement:</strong> These Terms constitute the
              entire agreement between you and Aligned AI.
            </li>
            <li>
              <strong>Severability:</strong> If any provision is found invalid,
              the remaining provisions remain in effect.
            </li>
            <li>
              <strong>No Waiver:</strong> Failure to enforce any provision does
              not constitute a waiver.
            </li>
          </ul>

          <h2>16. Contact Us</h2>
          <p>For questions about these Terms, contact us at:</p>
          <ul>
            <li>
              <strong>Email:</strong> legal@aligned.ai
            </li>
            <li>
              <strong>Support:</strong> hello@aligned.ai
            </li>
          </ul>
        </div>
      </section>

      <SiteFooter />
    </UnauthenticatedLayout>
  );
}
