/**
 * AI Generation Worker
 * 
 * Handles communication with OpenAI and Claude APIs
 * Provides configurable switching between providers
 * Loads and processes prompt templates
 */

import OpenAI from "openai";
import Anthropic from "@anthropic-ai/sdk";
import { readFile } from "fs/promises";
import { join } from "path";

export type AIProvider = "openai" | "claude";

// Initialize clients only when needed and API keys are available
let openaiClient: OpenAI | null = null;
let anthropicClient: Anthropic | null = null;

function getOpenAI(): OpenAI | null {
  if (openaiClient === null && process.env.OPENAI_API_KEY) {
    try {
      openaiClient = new OpenAI({ 
        apiKey: process.env.OPENAI_API_KEY,
        timeout: 30000,
      });
    } catch (error) {
      console.warn("Failed to initialize OpenAI client:", error);
      return null;
    }
  }
  return openaiClient;
}

function getAnthropic(): Anthropic | null {
  if (anthropicClient === null && process.env.ANTHROPIC_API_KEY) {
    try {
      anthropicClient = new Anthropic({ 
        apiKey: process.env.ANTHROPIC_API_KEY,
        timeout: 30000,
      });
    } catch (error) {
      console.warn("Failed to initialize Anthropic client:", error);
      return null;
    }
  }
  return anthropicClient;
}

// Default to OpenAI, fallback to Claude
function getDefaultProvider(): AIProvider {
  if (process.env.OPENAI_API_KEY) return "openai";
  if (process.env.ANTHROPIC_API_KEY) return "claude";
  return "openai"; // fallback
}

/**
 * Generate content using configured AI provider
 */
export async function generateWithAI(
  prompt: string, 
  agentType: "doc" | "design" | "advisor",
  provider?: AIProvider
): Promise<string> {
  const selectedProvider = provider || getDefaultProvider();
  
  try {
    if (selectedProvider === "openai") {
      const client = getOpenAI();
      if (!client) {
        throw new Error("OpenAI client not available - check OPENAI_API_KEY");
      }
      return await generateWithOpenAI(prompt, agentType, client);
    } else if (selectedProvider === "claude") {
      const client = getAnthropic();
      if (!client) {
        throw new Error("Anthropic client not available - check ANTHROPIC_API_KEY");
      }
      return await generateWithClaude(prompt, agentType, client);
    } else {
      throw new Error(`Unknown provider: ${selectedProvider}`);
    }
  } catch (error) {
    console.error(`AI generation failed with ${selectedProvider}:`, error);
    
    // Try fallback provider only if the error isn't a configuration issue
    if (error instanceof Error && !error.message.includes("not available")) {
      const fallbackProvider = selectedProvider === "openai" ? "claude" : "openai";
      
      try {
        if (fallbackProvider === "openai") {
          const client = getOpenAI();
          if (client) {
            console.log("Retrying with OpenAI...");
            return await generateWithOpenAI(prompt, agentType, client);
          }
        } else {
          const client = getAnthropic();
          if (client) {
            console.log("Retrying with Claude...");
            return await generateWithClaude(prompt, agentType, client);
          }
        }
      } catch (fallbackError) {
        console.error(`Fallback also failed:`, fallbackError);
      }
    }
    
    throw new Error(`AI generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

/**
 * Generate content using OpenAI
 */
async function generateWithOpenAI(prompt: string, agentType: string, client: OpenAI): Promise<string> {
  const model = getOpenAIModel(agentType);
  
  try {
    const response = await client.chat.completions.create({
      model,
      messages: [
        {
          role: "system",
          content: prompt
        }
      ],
      temperature: getTemperature(agentType),
      max_tokens: getMaxTokens(agentType),
      presence_penalty: 0.1,
      frequency_penalty: 0.1
    });

    const content = response.choices[0]?.message?.content;
    if (!content) {
      throw new Error("No content generated by OpenAI");
    }

    return content;
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`OpenAI API error: ${error.message}`);
    }
    throw error;
  }
}

/**
 * Generate content using Claude
 */
async function generateWithClaude(prompt: string, agentType: string, client: Anthropic): Promise<string> {
  const model = getClaudeModel(agentType);
  
  try {
    const response = await client.messages.create({
      model,
      max_tokens: getMaxTokens(agentType),
      temperature: getTemperature(agentType),
      messages: [
        {
          role: "user",
          content: prompt
        }
      ]
    });

    const content = response.content[0];
    if (!content || content.type !== "text") {
      throw new Error("Unexpected response type from Claude");
    }

    return content.text;
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Anthropic API error: ${error.message}`);
    }
    throw error;
  }
}

/**
 * Load prompt template from file system
 */
export async function loadPromptTemplate(
  agent: "doc" | "design" | "advisor",
  version: string = "v1.0",
  locale: string = "en"
): Promise<string> {
  try {
    const templatePath = join(process.cwd(), "prompts", agent, locale, `${version}.md`);
    const template = await readFile(templatePath, "utf-8");
    
    // Extract just the system prompt content (skip markdown headers)
    const lines = template.split('\n');
    const startIndex = lines.findIndex(line => line.includes('## SYSTEM ROLE') || line.includes('You are'));
    
    if (startIndex === -1) {
      return template; // Return full template if no clear start found
    }
    
    return lines.slice(startIndex).join('\n');
  } catch (error) {
    console.error(`Failed to load template for ${agent} ${version}:`, error);
    
    // Fallback templates
    return getFallbackTemplate(agent);
  }
}

/**
 * Get OpenAI model based on agent type
 */
function getOpenAIModel(agentType: string): string {
  switch (agentType) {
    case "doc":
      return "gpt-4o-mini"; // Good for text generation
    case "design":
      return "gpt-4o-mini"; // Good for structured output
    case "advisor":
      return "gpt-4o"; // Best for analysis and reasoning
    default:
      return "gpt-4o-mini";
  }
}

/**
 * Get Claude model based on agent type
 */
function getClaudeModel(agentType: string): string {
  switch (agentType) {
    case "doc":
      return "claude-3-5-haiku-20241022"; // Fast for text generation
    case "design":
      return "claude-3-5-sonnet-20241022"; // Good for structured output
    case "advisor":
      return "claude-3-5-sonnet-20241022"; // Best for analysis
    default:
      return "claude-3-5-haiku-20241022";
  }
}

/**
 * Get temperature setting based on agent type
 */
function getTemperature(agentType: string): number {
  switch (agentType) {
    case "doc":
      return 0.7; // Creative but controlled
    case "design":
      return 0.5; // More structured
    case "advisor":
      return 0.3; // Analytical and consistent
    default:
      return 0.7;
  }
}

/**
 * Get max tokens based on agent type
 */
function getMaxTokens(agentType: string): number {
  switch (agentType) {
    case "doc":
      return 1000; // Enough for social posts
    case "design":
      return 500; // Structured output
    case "advisor":
      return 1500; // Detailed analysis
    default:
      return 1000;
  }
}

/**
 * Fallback templates when files can't be loaded
 */
function getFallbackTemplate(agent: "doc" | "design" | "advisor"): string {
  const templates = {
    doc: `You are a professional content writer specializing in social media and marketing copy. 

Create engaging content that:
- Matches the brand voice and tone
- Includes a clear call-to-action
- Uses appropriate hashtags
- Stays within platform limits

Generate your response as JSON with these fields:
{
  "headline": "Attention-grabbing headline",
  "body": "Main content body",
  "cta": "Clear call-to-action",
  "hashtags": ["#relevant", "#hashtags"],
  "post_theme": "educational|promotional|story|testimonial",
  "tone_used": "professional|casual|friendly|bold",
  "aspect_ratio": "1080x1350|1080x1080|1920x1080"
}`,

    design: `You are a creative director specializing in social media visual design.

Create visual recommendations that:
- Use brand colors effectively
- Match the content theme
- Consider accessibility
- Provide clear layout guidance

Generate your response as JSON with these fields:
{
  "cover_title": "Short title for cover slide",
  "template_ref": "carousel-educational|single-image|video-thumbnail",
  "alt_text": "Detailed accessibility description",
  "visual_elements": ["list", "of", "design", "elements"],
  "color_palette_used": ["#color1", "#color2"],
  "font_suggestions": ["FontName", "weights"]
}`,

    advisor: `You are a data-driven social media strategist and advisor.

Analyze performance data to provide:
- Content topic recommendations
- Optimal posting times
- Format suggestions
- Strategic insights

Generate your response as JSON with these fields:
{
  "topics": [
    {
      "title": "Topic name",
      "rationale": "Why this works based on data",
      "confidence": 0.85
    }
  ],
  "best_times": [
    {
      "day": "Thursday",
      "slot": "18:00",
      "confidence": 0.8
    }
  ],
  "format_mix": {
    "reel": 0.4,
    "carousel": 0.4,
    "image": 0.2
  },
  "hashtags": ["#data-driven", "#hashtags"],
  "keywords": ["engagement", "growth", "insights"]
}`
  };

  return templates[agent];
}

/**
 * Check which AI providers are available
 */
export function getAvailableProviders(): AIProvider[] {
  const providers: AIProvider[] = [];
  
  if (process.env.OPENAI_API_KEY) {
    providers.push("openai");
  }
  
  if (process.env.ANTHROPIC_API_KEY) {
    providers.push("claude");
  }
  
  return providers;
}

/**
 * Validate that at least one AI provider is configured
 */
export function validateAIProviders(): boolean {
  const providers = getAvailableProviders();
  if (providers.length === 0) {
    console.error("No AI providers configured. Please set OPENAI_API_KEY or ANTHROPIC_API_KEY");
    return false;
  }
  console.log(`AI providers available: ${providers.join(", ")}`);
  return true;
}

// Export getDefaultProvider for use in other modules
export { getDefaultProvider };